import { el, sectionHeading, statRow } from "./dom";
import { formatMoney } from "./formatters";
import type { AnalyseResponse, VerifiedFacts } from "./ai-client";

function verifiedFactsSection(facts: VerifiedFacts): HTMLElement {
  const severity = facts.severityCounts;
  return el("div", { className: "ai-block verified" }, [
    el("h3", { className: "ai-block-title", text: "Verified facts" }),
    el("p", {
      className: "ai-block-source",
      text: "Computed by the application from the underlying records — not generated by the model.",
    }),
    statRow("Events analysed", String(facts.scope.eventCount)),
    statRow("Severity", `High ${severity.High ?? 0} · Moderate ${severity.Moderate ?? 0} · Low ${severity.Low ?? 0}`),
    statRow("Financial / Non-Financial", `${facts.eventTypeCounts.financial} / ${facts.eventTypeCounts.nonFinancial}`),
    statRow("Net (actual)", formatMoney(facts.actualExposure.net.total)),
    statRow("Potential impact", formatMoney(facts.potentialExposure.total)),
  ]);
}

function evidenceChips(eventIds: string[], onOpenEvent: (eventId: string) => void): HTMLElement | null {
  if (eventIds.length === 0) return null;
  const wrap = el("div", { className: "evidence-chips" });
  for (const eventId of eventIds.slice(0, 12)) {
    const chip = el("button", { className: "evidence-chip", text: eventId, attrs: { type: "button" } });
    chip.addEventListener("click", () => onOpenEvent(eventId));
    wrap.appendChild(chip);
  }
  return wrap;
}

/**
 * Renders the AI result with model-generated prose visually separated from
 * application-computed facts, so an analyst can never mistake one for the
 * other. All text is inserted as textContent, never as markup.
 */
export function renderAiResult(
  container: HTMLElement,
  result: AnalyseResponse,
  onOpenEvent: (eventId: string) => void,
): void {
  container.replaceChildren();

  const generated = new Date(result.generatedAt);
  container.appendChild(
    el("div", { className: "ai-meta" }, [
      el("span", { className: "ai-badge", text: "AI-generated analysis" }),
      el("span", {
        className: "ai-meta-text",
        text: `${result.model} · generated ${generated.toLocaleTimeString()} · evidence-based`,
      }),
    ]),
  );

  container.appendChild(verifiedFactsSection(result.verifiedFacts));

  const { analysis } = result;

  container.appendChild(
    el("div", { className: "ai-block interpretation" }, [
      el("h3", { className: "ai-block-title", text: "AI summary" }),
      el("p", { className: "narrative", text: analysis.summary }),
    ]),
  );

  if (analysis.observations.length > 0) {
    const block = el("div", { className: "ai-block interpretation" }, [
      el("h3", { className: "ai-block-title", text: "Observations" }),
    ]);
    for (const observation of analysis.observations) {
      block.appendChild(el("p", { className: "narrative", text: observation.statement }));
      const chips = evidenceChips(observation.evidenceEventIds, onOpenEvent);
      if (chips) block.appendChild(chips);
    }
    container.appendChild(block);
  }

  if (analysis.interpretations.length > 0) {
    container.appendChild(
      el("div", { className: "ai-block interpretation" }, [
        el("h3", { className: "ai-block-title", text: "AI interpretation" }),
        ...analysis.interpretations.map((interpretation) =>
          el("p", { className: "narrative" }, [
            el("span", { className: `confidence ${interpretation.confidence}`, text: interpretation.confidence }),
            document.createTextNode(` ${interpretation.statement}`),
          ]),
        ),
      ]),
    );
  }

  if (analysis.investigationQuestions.length > 0) {
    container.appendChild(
      el("div", { className: "ai-block interpretation" }, [
        el("h3", { className: "ai-block-title", text: "Investigation questions" }),
        el(
          "ul",
          { className: "ai-list" },
          analysis.investigationQuestions.map((question) => el("li", { text: question })),
        ),
      ]),
    );
  }

  if (analysis.recommendedActions.length > 0) {
    container.appendChild(
      el("div", { className: "ai-block interpretation" }, [
        el("h3", { className: "ai-block-title", text: "Suggested actions" }),
        el(
          "ul",
          { className: "ai-list" },
          analysis.recommendedActions.map((action) =>
            el("li", {}, [
              el("strong", { text: action.action }),
              document.createTextNode(` — ${action.reason}`),
            ]),
          ),
        ),
      ]),
    );
  }

  if (analysis.limitations.length > 0) {
    container.appendChild(
      el("div", { className: "ai-block limitations" }, [
        el("h3", { className: "ai-block-title", text: "Limitations" }),
        el(
          "ul",
          { className: "ai-list" },
          analysis.limitations.map((limitation) => el("li", { text: limitation })),
        ),
      ]),
    );
  }
}

export function renderAiMessage(container: HTMLElement, message: string, variant: "info" | "error"): void {
  container.replaceChildren(el("p", { className: variant === "error" ? "ai-error" : "empty-state", text: message }));
}

export { sectionHeading };
