import type { EventType, Severity, StreamEvent } from "../types/Event";
import type { Granularity, GroupByDimension } from "../types/Filters";
import type { Period, StreamPoint, StreamSeriesData } from "../types/Timeline";
import {
  EVENT_TYPE_STACK_ORDER,
  SEVERITY_STACK_ORDER,
  shortOrganisationName,
} from "../config/constants";
import {
  addDays,
  compareIsoDate,
  formatMonthLabel,
  formatWeekLabel,
  getMonthBounds,
  getWeekBounds,
  parseIsoDate,
} from "../utils/dateUtils";
import { filterByDateRange } from "./FilterService";

/**
 * Dynamically derives every time bucket present in the given (already
 * filtered) event set — no precomputed monthly/weekly JSON. Buckets are
 * generated by walking every distinct calendar month/week present in the
 * data, so gaps (periods with zero matching events) are simply absent rather
 * than rendered as empty buckets.
 */
export function generatePeriods(events: StreamEvent[], granularity: Granularity): Period[] {
  const bucketMap = new Map<string, Period>();

  for (const event of events) {
    const date = parseIsoDate(event.occurrenceDate);

    if (granularity === "month") {
      const { monthId, startDate, endDate } = getMonthBounds(date);
      if (!bucketMap.has(monthId)) {
        bucketMap.set(monthId, {
          id: `month:${monthId}`,
          granularity: "month",
          startDate,
          endDate,
          pointDate: endDate,
          label: formatMonthLabel(monthId),
        });
      }
    } else {
      const { mondayDate, startDate, endDate } = getWeekBounds(date);
      if (!bucketMap.has(mondayDate)) {
        bucketMap.set(mondayDate, {
          id: `week:${mondayDate}`,
          granularity: "week",
          startDate,
          endDate,
          pointDate: endDate,
          label: formatWeekLabel(startDate, endDate),
        });
      }
    }
  }

  return [...bucketMap.values()].sort((a, b) => compareIsoDate(a.startDate, b.startDate));
}

export function getEventsInPeriod(events: StreamEvent[], period: Period): StreamEvent[] {
  return filterByDateRange(events, period.startDate, period.endDate);
}

/**
 * The immediately preceding comparable bucket for a period, computed purely
 * from calendar arithmetic (previous month, or the 7 days immediately before
 * this week's Monday) — independent of which periods actually contain events.
 */
export function getPreviousPeriod(period: Period): Period {
  if (period.granularity === "month") {
    const dayBeforeStart = addDays(parseIsoDate(period.startDate), -1);
    const { monthId, startDate, endDate } = getMonthBounds(dayBeforeStart);
    return {
      id: `month:${monthId}`,
      granularity: "month",
      startDate,
      endDate,
      pointDate: endDate,
      label: formatMonthLabel(monthId),
    };
  }

  const previousMonday = addDays(parseIsoDate(period.startDate), -7);
  const { mondayDate, startDate, endDate } = getWeekBounds(previousMonday);
  return {
    id: `week:${mondayDate}`,
    granularity: "week",
    startDate,
    endDate,
    pointDate: endDate,
    label: formatWeekLabel(startDate, endDate),
  };
}

function seriesKeyFor(event: StreamEvent, groupBy: GroupByDimension): string {
  switch (groupBy) {
    case "riskTheme":
      return event.riskTheme;
    case "severity":
      return event.severity;
    case "organisation":
      return shortOrganisationName(event.ownerOrganisation);
    case "eventType":
      return event.eventType;
  }
}

/** Fixed series ordering per dimension so stacked series never swap vertical position between renders. */
export function getStableSeriesOrder(events: StreamEvent[], groupBy: GroupByDimension): string[] {
  if (groupBy === "severity") return [...SEVERITY_STACK_ORDER] as Severity[] as string[];
  if (groupBy === "eventType") return [...EVENT_TYPE_STACK_ORDER] as EventType[] as string[];
  if (groupBy === "organisation") {
    return [...new Set(events.map((e) => shortOrganisationName(e.ownerOrganisation)))].sort();
  }
  return [...new Set(events.map((e) => e.riskTheme))].sort();
}

export function buildStreamSeriesData(
  events: StreamEvent[],
  granularity: Granularity,
  groupBy: GroupByDimension,
): StreamSeriesData {
  const periods = generatePeriods(events, granularity);
  const seriesKeys = getStableSeriesOrder(events, groupBy);

  const points: StreamPoint[] = periods.map((period) => {
    const periodEvents = getEventsInPeriod(events, period);
    const series: Record<string, number> = {};
    for (const key of seriesKeys) series[key] = 0;
    for (const event of periodEvents) {
      const key = seriesKeyFor(event, groupBy);
      series[key] = (series[key] ?? 0) + 1;
    }
    return {
      periodId: period.id,
      pointDate: period.pointDate,
      label: period.label,
      total: periodEvents.length,
      series,
    };
  });

  return { seriesKeys, points };
}

export function findPeriodById(events: StreamEvent[], granularity: Granularity, periodId: string): Period | null {
  return generatePeriods(events, granularity).find((p) => p.id === periodId) ?? null;
}
